spring:
  application:
    name: learn-graphql-java
server:
  http2:
    enabled: true
graphql:
  servlet:
    max-query-depth: 5
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphqls
        variables: classpath:playground/bank_account_variables.graphqls